import Head from 'next/head'
import Image from 'next/image'
import Reading from '../components/Reading'
import Shop from '../components/Shop'
import Link from 'next/link'
import Content from '../components/Content'
import Caroselle from '../components/Carousel'




export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <Caroselle/>
    <Content/>
    <Reading/>
    <Shop />



    </>
  )
}
